In [67]:
import numpy as np
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from rich import print
from sklearn.metrics import accuracy_score

In [197]:
# information about each csv file seperatly.
customers = pd.read_csv('customers.csv')
Items = pd.read_csv('Items.csv')
order_item = pd.read_csv('order_item.csv')
orders = pd.read_csv('orders.csv')
display('customers', customers,'Items' , Items, 'order_item', order_item, 'orders', orders)
%config Completer.use_jedi = False

'customers'

,id,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
0,1,Eadie,Maffeo,Female,41.0,France,2022-01-11,534-341-9052,emaffeo0@smh.com.au
1,2,Hammad,Brewerton,Male,56.0,Isreal,2022-09-30,999-994-0510,hbrewerton1@discovery.com
2,3,Terrell,Bris,NaN,43.0,India,NaN,980-455-5208,tbris2@yale.edu
3,4,Frannie,Morewood,Male,84.0,France,2021-05-26,979-187-1493,fmorewood3@vistaprint.com
4,5,Sophi,Fleet,Female,33.0,Sweden,2021-07-19,991-853-9984,sfleet4@unicef.org
...,...,...,...,...,...,...,...,...,...
495,496,Renado,Monard,Male,53.0,India,NaN,399-472-4819,rmonarddr@yale.edu
496,497,Kalina,Luno,Female,30.0,Italy,2022-10-16,659-768-2522,klunods@friendfeed.com
497,498,Viv,Callander,Female,44.0,France,2021-02-24,447-685-9318,vcallanderdt@icq.com
498,499,Georg,Raper,Male,41.0,Germany,2022-04-24,863-207-4830,graperdu@homestead.com
499,500,Richardo,O'Criane,Male,32.0,United States,2021-08-06,796-438-2219,rocrianedv@geocities.com

'Items'

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability
0,1,Television,Televisions and Displays,356.81,1009.0,NaN,True
1,2,Laptop,Computers and Accessories,1851.32,493.0,NaN,True
2,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True
3,4,Smartphone,Mobile Devices and Accessories,965.20,201.0,NaN,True
4,5,Tablet,NaN,2739.61,190.0,Toshiba,True
5,6,Printer,Printers and Office Equipment,4175.99,971.0,Sony,True
6,7,Camera,Photography Equipment,2366.72,458.0,NaN,True
7,8,Headphone,NaN,3117.19,599.0,NaN,True
8,9,Speaker,Audio Equipment,4471.27,1360.0,Toshiba,True
9,10,DVD Player,Video Players and Recorders,453.85,605.0,NaN,True
10,11,Blu-Ray Player,Video Players and Recorders,3382.86,704.0,ASUS,True
11,12,Video Game Console,Gaming Equipment,689.61,753.0,Microsoft,True
12,13,Video Game,NaN,1890.03,681.0,Lenovo,True
13,14,Smart Watch,Mobile Devices and Accessories,2007.43,742.0,Logitech,True
14,15,Fitness Tracker,Mobile Devices and Accessories,2997.29,956.0,Apple,True
15,16,Drone,NaN,3949.97,850.0,Logitech,True
16,17,Projector,Televisions and Displays,312.88,685.0,Canon,True
17,18,Computer Monitor,Computers and Accessories,4076.35,1205.0,Bose,True
18,19,Keyboard,Computers and Accessories,604.18,NaN,Panasonic,False
19,20,Mouse,Computers and Accessories,1333.04,881.0,Logitech,True
20,21,External Hard Drive,Computers and Accessories,1251.36,1013.0,Microsoft,True
21,22,USB Flash Drive,NaN,1150.87,1251.0,Panasonic,True
22,23,Micro SD Card,Storage Devices,3238.23,663.0,Sony,True
23,24,Digital Picture Frame,Televisions and Displays,4449.99,443.0,Samsung,True
24,25,Camcorder,Photography Equipment,860.01,870.0,Bose,True
25,26,Action Camera,Photography Equipment,2694.25,NaN,Bose,False
26,27,Dash Camera,Photography Equipment,1283.99,550.0,Lenovo,True
27,28,CCTV Camera,NaN,695.71,NaN,Sony,False
28,29,Webcam,Printers and Office Equipment,4227.36,596.0,Dell,True
29,30,Gaming Chair,Gaming Equipment,417.16,704.0,Samsung,True
30,31,Wireless Charger,Mobile Devices and Accessories,241.54,951.0,Lenovo,True
31,32,Portable Charger,Mobile Devices and Accessories,1523.27,192.0,HP,True
32,33,Surge Protector,Printers and Office Equipment,488.39,800.0,ASUS,True
33,34,HDMI Cable,Cables,1710.84,869.0,JBL,True
34,35,Wi-Fi Router,Network Equipment,3812.53,14.0,Microsoft,True
35,36,Modem,NaN,3256.88,673.0,Bose,True
36,37,Antivirus Software,Software,4186.62,NaN,NaN,False
37,38,Office Software,Printers and Office Equipment,3454.82,643.0,JBL,True
38,39,Power Strip,Printers and Office Equipment,3344.90,1211.0,HP,True
39,40,Tripod,Photography Equipment,2055.66,1072.0,Nintendo,True
40,41,VR Headset,NaN,1905.01,1367.0,JBL,True
41,42,Television,Televisions and Displays,479.19,670.0,Samsung,True
42,43,Laptop,Computers and Accessories,4153.61,1018.0,Dell,True
43,44,Desktop,Computers and Accessories,723.59,1119.0,NaN,True
44,45,Smartphone,Mobile Devices and Accessories,3513.56,1162.0,Panasonic,True
45,46,Tablet,Mobile Devices and Accessories,1606.65,267.0,HP,True
46,47,Printer,Printers and Office Equipment,3704.16,239.0,NaN,True
47,48,Camera,Photography Equipment,2039.08,471.0,Panasonic,True
48,49,Headphone,Audio Equipment,1317.56,NaN,Sony,False
49,50,Speaker,Audio Equipment,4453.90,937.0,NaN,True

'order_item'

     Unnamed: 0    id  order_id  item_id  quantity
0             0     1       337     10.0         2
1             1     2       430     27.0         6
2             2     3       430     36.0         2
3             3     4       508     46.0         1
4             4     5       229     27.0         2
..          ...   ...       ...      ...       ...
995         995   996       594     24.0         2
996         996   997       330     32.0         8
997         997   998       472     10.0         3
998         998   999       222     29.0         1
999         999  1000       337     16.0         1

[1000 rows x 5 columns]

'orders'

,order_id,customer_id,delivery_address,delivery_days,order_date,payment_method,order_source
0,1,477.0,576 Cordelia Place,2.0,2023-12-05,GIFT_CARD,WEBSITE
1,2,93.0,4664 6th Drive,4.0,2023-08-17,CASH,STORE
2,3,474.0,8766 4th Point,4.0,2023-02-25,CHECK,STORE
3,4,333.0,31 Bonner Way,3.0,2023-02-04,CASH,STORE
4,5,436.0,20352 Shelley Way,5.0,2023-06-01,CASH,STORE
...,...,...,...,...,...,...,...
595,596,110.0,26 Hudson Lane,5.0,2023-10-30,CREDIT_CARD,WEBSITE
596,597,209.0,37392 Sullivan Park,4.0,2023-08-23,CREDIT_CARD,WEBSITE
597,598,480.0,1473 Ilene Drive,4.0,2023-09-11,CASH,STORE
598,599,72.0,2 Nancy Crossing,4.0,2023-02-09,CASH,STORE
599,600,169.0,545 Orin Lane,3.0,2023-02-16,GIFT_CARD,WEBSITE

In [69]:
# Qestion 1:
# part 1- Data Investigation:

# Func in use is info(), with a title for each.

print(f'\ncustomers info\n')
customers.info()
print(f'\nItems info\n')
Items.info()
print(f'\norder_item info\n')    
order_item.info()
print(f'\norders info\n')
orders.info()

# describing every file (including MIN, MAX, AVG, median & more) for each csv file seperatly.
    # Func in use is describe(include='all'), with a title for each.

display('customers - describe', customers.describe(include='all').T.reset_index(names='columns'),
       'Items - describe', Items.describe(include='all').T.reset_index(names='columns'),
       'order_item - describe', order_item.describe(include='all').T.reset_index(names='columns'),
       'orders - describe',orders.describe(include='all').T.reset_index(names='columns'))

# displaying the first 5 rows for each csv file
    # Func in use is head(), for 5 first rows there is no need for specified number of roes, with a title for each.

display('customers first 5:', customers.head(),
'Items first 5:', Items.head(),
'order_item first 5', order_item.head(),
'orders first 5', orders.head())

customers info

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            500 non-null    int64
 1   first_name    500 non-null    str
 2   last_name     500 non-null    str
 3   gender        442 non-null    str
 4   age           475 non-null    float64
 5   nationallity  500 non-null    str
 6   joining_date  439 non-null    str
 7   phone_number  492 non-null    str
 8   email         500 non-null    str
dtypes: float64(1), int64(1), str(7)
memory usage: 35.3 KB

Items info

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 50 non-null     int64
 1   item_name          50 non-null     str
 2   item_category      42 non-null     str
 3   item_price         50 non-null     float64
 4   stock_quantity     45 non-null     float64
 5   item_brand         40 non-null     str
 6   item_availability  50 non-null     bool
dtypes: bool(1), float64(2), int64(1), str(3)
memory usage: 2.5 KB

order_item info

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   id          1000 non-null   int64
 2   order_id    1000 non-null   int64
 3   item_id     960 non-null    float64
 4   quantity    1000 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 39.2 KB

orders info

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          600 non-null    int64
 1   customer_id       555 non-null    float64
 2   delivery_address  600 non-null    str
 3   delivery_days     525 non-null    float64
 4   order_date        600 non-null    str
 5   payment_method    600 non-null    str
 6   order_source      600 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 32.9 KB

'customers - describe'

,columns,count,unique,top,freq,mean,std,min,25%,50%,75%,max
0,id,500.0,NaN,NaN,NaN,250.5,144.481833,1.0,125.75,250.5,375.25,500.0
1,first_name,500,490,Lynne,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,last_name,500,497,Swatten,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,gender,442,8,Female,201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,age,475.0,NaN,NaN,NaN,44.006316,14.813395,2.0,34.0,44.0,55.0,84.0
5,nationallity,500,15,United States,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,joining_date,439,368,2020-08-02,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,phone_number,492,492,534-341-9052,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,email,500,500,emaffeo0@smh.com.au,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

'Items - describe'

,columns,count,unique,top,freq,mean,std,min,25%,50%,75%,max
0,id,50.0,NaN,NaN,NaN,25.5,14.57738,1.0,13.25,25.5,37.75,50.0
1,item_name,50,41,Television,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,item_category,42,12,Computers and Accessories,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,item_price,50.0,NaN,NaN,NaN,2222.0826,1394.005145,241.54,1004.36,1956.22,3436.83,4471.27
4,stock_quantity,45.0,NaN,NaN,NaN,743.155556,332.855071,14.0,550.0,704.0,971.0,1367.0
5,item_brand,40,15,HP,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,item_availability,50,2,True,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN

'order_item - describe'

,columns,count,mean,std,min,25%,50%,75%,max
0,Unnamed: 0,1000.0,499.500000,288.819436,0.0,249.75,499.5,749.25,999.0
1,id,1000.0,500.500000,288.819436,1.0,250.75,500.5,750.25,1000.0
2,order_id,1000.0,305.006000,171.251432,1.0,157.00,315.0,450.00,599.0
3,item_id,960.0,25.746875,14.676686,1.0,13.00,26.0,38.00,50.0
4,quantity,1000.0,3.016000,2.288882,1.0,1.00,2.0,4.00,9.0

'orders - describe'

,columns,count,unique,top,freq,mean,std,min,25%,50%,75%,max
0,order_id,600.0,NaN,NaN,NaN,300.5,173.349358,1.0,150.75,300.5,450.25,600.0
1,customer_id,555.0,NaN,NaN,NaN,258.65045,146.002993,1.0,136.0,256.0,385.0,500.0
2,delivery_address,600,600,576 Cordelia Place,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,delivery_days,525.0,NaN,NaN,NaN,3.899048,1.075091,1.0,3.0,4.0,5.0,6.0
4,order_date,600,301,2023-01-24,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,payment_method,600,4,CASH,158,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,order_source,600,2,WEBSITE,328,NaN,NaN,NaN,NaN,NaN,NaN,NaN

'customers first 5:'

,id,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
0,1,Eadie,Maffeo,Female,41.0,France,2022-01-11,534-341-9052,emaffeo0@smh.com.au
1,2,Hammad,Brewerton,Male,56.0,Isreal,2022-09-30,999-994-0510,hbrewerton1@discovery.com
2,3,Terrell,Bris,NaN,43.0,India,NaN,980-455-5208,tbris2@yale.edu
3,4,Frannie,Morewood,Male,84.0,France,2021-05-26,979-187-1493,fmorewood3@vistaprint.com
4,5,Sophi,Fleet,Female,33.0,Sweden,2021-07-19,991-853-9984,sfleet4@unicef.org

'Items first 5:'

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability
0,1,Television,Televisions and Displays,356.81,1009.0,NaN,True
1,2,Laptop,Computers and Accessories,1851.32,493.0,NaN,True
2,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True
3,4,Smartphone,Mobile Devices and Accessories,965.20,201.0,NaN,True
4,5,Tablet,NaN,2739.61,190.0,Toshiba,True

'order_item first 5'

   Unnamed: 0  id  order_id  item_id  quantity
0           0   1       337     10.0         2
1           1   2       430     27.0         6
2           2   3       430     36.0         2
3           3   4       508     46.0         1
4           4   5       229     27.0         2

'orders first 5'

,order_id,customer_id,delivery_address,delivery_days,order_date,payment_method,order_source
0,1,477.0,576 Cordelia Place,2.0,2023-12-05,GIFT_CARD,WEBSITE
1,2,93.0,4664 6th Drive,4.0,2023-08-17,CASH,STORE
2,3,474.0,8766 4th Point,4.0,2023-02-25,CHECK,STORE
3,4,333.0,31 Bonner Way,3.0,2023-02-04,CASH,STORE
4,5,436.0,20352 Shelley Way,5.0,2023-06-01,CASH,STORE

In [194]:
# Qestion 1:
# part 2- Duplication Deletion:

######## Creating a new DF to replace 'Items', keeping the original as an archive.
Items_no_doubles = Items

######## removing Duplicate's based on greater amount of Non-null values:
Items_no_doubles = (Items.assign(Non_null_count = Items.count(axis=1))
    .sort_values( by = ['item_name', 'Non_null_count'], ascending= [False, False] )
    .drop_duplicates( subset = ['item_name'], keep ='first' ).sort_index())

######## maping id from items, maping replacment id's andreplacing it in order_item:
keep_Item_id_map = Items_no_doubles.set_index('item_name')['id']
Items_maped = Items[['id', 'item_name']].copy()
Items_maped['new_id'] = Items_maped['item_name'].map(keep_Item_id_map)

dict_replace = Items_maped.set_index('id')['new_id'].to_dict()
order_item['item_id'] = order_item['item_id'].map(dict_replace)
display("displaying only corrected item_id's, all Duplication's who has las non-null's had been removed", order_item)

###### if you want to precent ID sorted - apply this code:
    # 1.  check_replacment = order_item['item_id'].reset_index()
    # 2.  check_replacment.groupby('item_id').count() ''')

"displaying only corrected item_id's, all Duplication's who has las non-null's had been removed"

     Unnamed: 0    id  order_id  item_id  quantity
0             0     1       337     10.0         2
1             1     2       430     27.0         6
2             2     3       430     36.0         2
3             3     4       508     46.0         1
4             4     5       229     27.0         2
..          ...   ...       ...      ...       ...
995         995   996       594     24.0         2
996         996   997       330     32.0         8
997         997   998       472     10.0         3
998         998   999       222     29.0         1
999         999  1000       337     16.0         1

[1000 rows x 5 columns]

In [239]:
# ######## Creating a new DF to replace 'customers', keeping the original as an archived copy.
# customers_no_3_NaN = customers.copy().set_index('id')

# ######## Summing the missing values (NaNs) across rows.
# customers_no_3_NaN['count_null'] = customers_no_3_NaN.isna().sum(axis= 1)

# # Filtering out customers with 3 or more NaN values and rearranging the dataframe.
# customers_no_3_NaN = (customers_no_3_NaN.reset_index()
#     .set_index('count_null')
#     .sort_index(ascending= False)
#     .drop(index = 3)
#     .reset_index()
#     .set_index('id')
#     .sort_index()
#     .drop(columns='count_null'))
# display('rearranged & reorgenaized table after droping customers with 3 or more NaN', customers_no_3_NaN)

'rearranged & reorgenaized table after droping customers with 3 or more NaN'

,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
id,,,,,,,,
1,Eadie,Maffeo,Female,41.0,France,2022-01-11,534-341-9052,emaffeo0@smh.com.au
2,Hammad,Brewerton,Male,56.0,Isreal,2022-09-30,999-994-0510,hbrewerton1@discovery.com
3,Terrell,Bris,NaN,43.0,India,NaN,980-455-5208,tbris2@yale.edu
4,Frannie,Morewood,Male,84.0,France,2021-05-26,979-187-1493,fmorewood3@vistaprint.com
5,Sophi,Fleet,Female,33.0,Sweden,2021-07-19,991-853-9984,sfleet4@unicef.org
...,...,...,...,...,...,...,...,...
496,Renado,Monard,Male,53.0,India,NaN,399-472-4819,rmonarddr@yale.edu
497,Kalina,Luno,Female,30.0,Italy,2022-10-16,659-768-2522,klunods@friendfeed.com
498,Viv,Callander,Female,44.0,France,2021-02-24,447-685-9318,vcallanderdt@icq.com
499,Georg,Raper,Male,41.0,Germany,2022-04-24,863-207-4830,graperdu@homestead.com
500,Richardo,O'Criane,Male,32.0,United States,2021-08-06,796-438-2219,rocrianedv@geocities.com

"all valid ONLY, order_item ID's (DataFrame): "

     Unnamed: 0    id  order_id  item_id  quantity
0             0     1       337     10.0         2
1             1     2       430     27.0         6
2             2     3       430     36.0         2
3             3     4       508     46.0         1
4             4     5       229     27.0         2
..          ...   ...       ...      ...       ...
994         994   995       483     35.0         4
995         995   996       594     24.0         2
996         996   997       330     32.0         8
997         997   998       472     10.0         3
999         999  1000       337     16.0         1

[902 rows x 5 columns]

In [240]:
######## Summing the missing values (NaNs) across rows + Creating a new DF to replace 'customers'
cleand_customers = customers[customers.isna().sum(axis=1) <3].copy()
display('all valid ONLY, customers ONLY (DataFrame): ', cleand_customers)

######## filtering all not valid orders:
valid_customers = cleand_customers['id']

valid_Cids_orders = orders[orders['customer_id'].isin(valid_customers)]
valid_orders_ids = valid_Cids_orders['order_id']

######## filtering all not valid order_items:
cleaned_order_item = order_item[order_item['order_id'].isin(valid_orders_ids)]
display("all valid ONLY, order_item ID's (DataFrame): ", cleaned_order_item)

'all valid ONLY, customers ONLY (DataFrame): '

,id,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
0,1,Eadie,Maffeo,Female,41.0,France,2022-01-11,534-341-9052,emaffeo0@smh.com.au
1,2,Hammad,Brewerton,Male,56.0,Isreal,2022-09-30,999-994-0510,hbrewerton1@discovery.com
2,3,Terrell,Bris,NaN,43.0,India,NaN,980-455-5208,tbris2@yale.edu
3,4,Frannie,Morewood,Male,84.0,France,2021-05-26,979-187-1493,fmorewood3@vistaprint.com
4,5,Sophi,Fleet,Female,33.0,Sweden,2021-07-19,991-853-9984,sfleet4@unicef.org
...,...,...,...,...,...,...,...,...,...
495,496,Renado,Monard,Male,53.0,India,NaN,399-472-4819,rmonarddr@yale.edu
496,497,Kalina,Luno,Female,30.0,Italy,2022-10-16,659-768-2522,klunods@friendfeed.com
497,498,Viv,Callander,Female,44.0,France,2021-02-24,447-685-9318,vcallanderdt@icq.com
498,499,Georg,Raper,Male,41.0,Germany,2022-04-24,863-207-4830,graperdu@homestead.com
499,500,Richardo,O'Criane,Male,32.0,United States,2021-08-06,796-438-2219,rocrianedv@geocities.com

"all valid ONLY, order_item ID's (DataFrame): "

     Unnamed: 0    id  order_id  item_id  quantity
0             0     1       337     10.0         2
1             1     2       430     27.0         6
2             2     3       430     36.0         2
3             3     4       508     46.0         1
4             4     5       229     27.0         2
..          ...   ...       ...      ...       ...
994         994   995       483     35.0         4
995         995   996       594     24.0         2
996         996   997       330     32.0         8
997         997   998       472     10.0         3
999         999  1000       337     16.0         1

[902 rows x 5 columns]